CREATE TABLE IF NOT EXISTS postings (
    job_id            TEXT PRIMARY KEY,
    board_type        TEXT,
    title             TEXT,
    org               TEXT,
    location          TEXT,
    deadline          TEXT,
    deadline_iso      TEXT,
    work_term         TEXT,
    openings          INTEGER,
    apps_count        INTEGER,
    summary           TEXT,
    responsibilities  TEXT,
    required_skills   TEXT,
    raw_fields_json   TEXT,
    scraped_at        TEXT,
    updated_at        TEXT,
    status            TEXT NOT NULL DEFAULT 'new',
    embedding         BLOB,
    score_firmware          REAL,
    score_hardware          REAL,
    score_software          REAL,
    score_ai_ml             REAL,
    score_resume            REAL,
    comp_raw_text           TEXT,
    comp_native_min         REAL,
    comp_native_max         REAL,
    comp_currency           TEXT,
    comp_period             TEXT,
    comp_hours_per_week     REAL,
    comp_hourly_native_min  REAL,
    comp_hourly_native_max  REAL,
    comp_hourly_cad_min     REAL,
    comp_hourly_cad_max     REAL,
    comp_hourly_cad_mid     REAL,
    comp_fx_rate            REAL,
    comp_fx_date            TEXT,
    comp_parse_status       TEXT,
    comp_confidence         TEXT,
    comp_tiers_json         TEXT,
    comp_parser_version     INTEGER
);

-- Reserved for on-demand LLM fit evaluations, keyed by (resume_hash, job_id).
-- Not used in v1 of the UI.
CREATE TABLE IF NOT EXISTS llm_evals (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    resume_hash  TEXT NOT NULL,
    job_id       TEXT NOT NULL REFERENCES postings(job_id),
    eval_json    TEXT,
    created_at   TEXT,
    UNIQUE(resume_hash, job_id)
);
